version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1

  app:
    build: ./app
    container_name: s3-local-app
    depends_on:
      - localstack
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    command: python upload.py
